version: "3.5"

services:
  registry:
    container_name: registry
    networks:
      - registry-network
    restart: always
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./config/registry-config.yml:/etc/docker/registry/config.yml:ro
      - ./registry-data:/var/lib/registry:rw

networks:
  registry-network:
    driver: bridge
    name: registry-network
