version: "3.5"

services:
  registry:
    container_name: registry
    networks:
      - kaniko-local
    restart: always
    image: registry:2.8.3
    ports:
      - 5000:5000
    volumes:
      - ./config/registry-config.yml:/etc/docker/registry/config.yml:ro
      - ./registry-data:/var/lib/registry:rw
    #   - ./auth:/auth
    # environment:
    #   - REGISTRY_AUTH=htpasswd
    #   - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
    #   - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd

networks:
  kaniko-local:
    driver: bridge
    name: kaniko-local
